baseURL = "https://tangerrini.github.io/coolspot/"
locale = "en-us"
title = "coolspot"
theme = "berenice"

timeout = "120s"

[params]
HugoFooter = false

[params.author]
name = "Your name"
email = "your@family.name"