baseURL: "https://tangerrini.github.io/coolspot/" # todo: change site url.
title: "coolspot" # todo: change site name.
defaultContentLanguage: 'en'
theme: eternity
googleAnalytics: '' # todo: set your analytics id.

params:
  image: /images/banner.png
  logo: logo.png # todo: add your custom logo to static/
  subtitle: Eternity is a minimalist Hugo theme designed for portfolio sites with a fresh feel. # todo: change default subtitle for your website.
  copyright: All rights reserved. # todo: set your copyright type.
  author: Lovely Author # todo: set your full name.
  dontShowSource: false # please, do not do this :)
  portfolio:
    columns:
      desktop:
        about: 4
        sketches: 6
        photos: 2
        archive: 3
        default: 2
      mobile:
        about: 4
        sketches: 6
        photos: 2
        archive: 3
        default: 2
  socials:
    # todo: change these links.
    - icon: 'far fa-envelope fa-lg'
      url: 'mailto: ...'
      landing: true
    - icon: 'fab fa-github fa-lg'
      url: ''
      landing: true
    # - icon: 'fab fa-instgrm fa-lg'
    #   url: ''
    # - icon: 'fab fa-linkedin-in fa-lg'
    #   url: ''
  homepage: "/work" # homepage link, mostly same with menu.main[0]
  specialPages:
    - work
    - archive
  bypassWelcomePage: false # redirects "/" to "homepage" when it's true.
  disableWelcomePageBackground: false # disables the background image on the homepage
  plausible: '' # todo: set your plausible id.
  disableRadius: false
  moveIt: false  # Moves Title and Meta info down, only visible when scroll.
  disableAlwaysResize: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  tag: tags

permalinks:
  work: "/:contentbasename/"

menu:
  main:
    - name: about
      url: /about/
      weight: 1
    - name: sketches
      url: /sketches/
      weight: 2
    - name: photos
      url: /photos/
      weight: 3
    - name: archive
      url: /tags/archive/
      weight: 4
