baseURL = "https://tangerrini.github.io/coolspot/"
title = "coolspot"
theme = "berenice"
defaultContentLanguage = "en"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
author = "Your Name"
description = "Personal media gallery"